export const SUPPORTED_CHAINS = [
  // 1. Ethereum Mainnet
  {
    id: 'ethereum',
    chainId: 1,
    name: 'Ethereum Mainnet',
    shortName: 'Ethereum',
    symbol: 'ETH',
    decimals: 18,
    icon: '⚡',
    color: '#627EEA',
    rpcUrl: 'https://cloudflare-eth.com',
    explorerUrl: 'https://etherscan.io',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 2. Base
  {
    id: 'base',
    chainId: 8453,
    name: 'Base Mainnet',
    shortName: 'Base',
    symbol: 'ETH',
    decimals: 18,
    icon: '🔵',
    color: '#0052FF',
    rpcUrl: 'https://mainnet.base.org',
    explorerUrl: 'https://basescan.org',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 3. Arbitrum One
  {
    id: 'arbitrum',
    chainId: 42161,
    name: 'Arbitrum One',
    shortName: 'Arbitrum',
    symbol: 'ETH',
    decimals: 18,
    icon: '💙',
    color: '#28A0F0',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    explorerUrl: 'https://arbiscan.io',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 4. OP Mainnet (Optimism)
  {
    id: 'optimism',
    chainId: 10,
    name: 'OP Mainnet (Optimism)',
    shortName: 'Optimism',
    symbol: 'ETH',
    decimals: 18,
    icon: '🔴',
    color: '#FF0420',
    rpcUrl: 'https://mainnet.optimism.io',
    explorerUrl: 'https://optimistic.etherscan.io',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 5. Polygon Mainnet
  {
    id: 'polygon',
    chainId: 137,
    name: 'Polygon Mainnet',
    shortName: 'Polygon',
    symbol: 'POL',
    decimals: 18,
    icon: '💜',
    color: '#8247E5',
    rpcUrl: 'https://polygon-bor-rpc.publicnode.com',
    explorerUrl: 'https://polygonscan.com',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 6. Sei Network EVM
  {
    id: 'sei',
    chainId: 1329,
    name: 'Sei Network EVM',
    shortName: 'Sei',
    symbol: 'SEI',
    decimals: 18,
    icon: '🔴',
    color: '#9B1C1C',
    rpcUrl: 'https://evm-rpc.sei-apis.com',
    explorerUrl: 'https://seitrace.com',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 7. ApeChain
  {
    id: 'apechain',
    chainId: 33139,
    name: 'ApeChain',
    shortName: 'ApeChain',
    symbol: 'APE',
    decimals: 18,
    icon: '🦍',
    color: '#0052FF',
    rpcUrl: 'https://rpc.apechain.com/http',
    explorerUrl: 'https://apescan.io',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 8. Berachain
  {
    id: 'berachain',
    chainId: 80094,
    name: 'Berachain Mainnet',
    shortName: 'Berachain',
    symbol: 'BERA',
    decimals: 18,
    icon: '🐻',
    color: '#E07A27',
    rpcUrl: 'https://rpc.berachain.com',
    explorerUrl: 'https://berascan.com',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 9. Soneium (Sony L2)
  {
    id: 'soneium',
    chainId: 1868,
    name: 'Soneium Mainnet (Sony)',
    shortName: 'Soneium',
    symbol: 'ETH',
    decimals: 18,
    icon: '🌐',
    color: '#003791',
    rpcUrl: 'https://rpc.soneium.org/',
    explorerUrl: 'https://soneium.blockscout.com',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 10. Unichain (Uniswap L2)
  {
    id: 'unichain',
    chainId: 130,
    name: 'Unichain Mainnet',
    shortName: 'Unichain',
    symbol: 'ETH',
    decimals: 18,
    icon: '🦄',
    color: '#FF007A',
    rpcUrl: 'https://mainnet.unichain.org',
    explorerUrl: 'https://uniscan.xyz',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 11. Abstract (Igloo L2)
  {
    id: 'abstract',
    chainId: 2741,
    name: 'Abstract Mainnet',
    shortName: 'Abstract',
    symbol: 'ETH',
    decimals: 18,
    icon: '🧊',
    color: '#00F5D4',
    rpcUrl: 'https://api.mainnet.abs.xyz',
    explorerUrl: 'https://abscan.org',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 12. Shape Network
  {
    id: 'shape',
    chainId: 360,
    name: 'Shape Network',
    shortName: 'Shape',
    symbol: 'ETH',
    decimals: 18,
    icon: '📐',
    color: '#00E599',
    rpcUrl: 'https://mainnet.shape.network',
    explorerUrl: 'https://shapescan.xyz',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 13. Zora Network
  {
    id: 'zora',
    chainId: 7777777,
    name: 'Zora Network',
    shortName: 'Zora',
    symbol: 'ETH',
    decimals: 18,
    icon: '🌐',
    color: '#000000',
    rpcUrl: 'https://rpc.zora.energy',
    explorerUrl: 'https://explorer.zora.energy',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 14. Blast Mainnet
  {
    id: 'blast',
    chainId: 81457,
    name: 'Blast Mainnet',
    shortName: 'Blast',
    symbol: 'ETH',
    decimals: 18,
    icon: '💥',
    color: '#FCFC03',
    rpcUrl: 'https://rpc.blast.io',
    explorerUrl: 'https://blastscan.io',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 15. B3 Network (Base L3)
  {
    id: 'b3',
    chainId: 8333,
    name: 'B3 Network',
    shortName: 'B3',
    symbol: 'ETH',
    decimals: 18,
    icon: '🎲',
    color: '#3B82F6',
    rpcUrl: 'https://mainnet-rpc.b3.fun/http',
    explorerUrl: 'https://explorer.b3.fun',
    category: 'Layer 3',
    openseaSupported: true,
  },
  // 16. Ronin Network
  {
    id: 'ronin',
    chainId: 2020,
    name: 'Ronin Network',
    shortName: 'Ronin',
    symbol: 'RON',
    decimals: 18,
    icon: '⚔️',
    color: '#1273EA',
    rpcUrl: 'https://api.roninchain.com/rpc',
    explorerUrl: 'https://app.roninchain.com',
    category: 'Gaming L1',
    openseaSupported: true,
  },
  // 17. Flow EVM
  {
    id: 'flow',
    chainId: 747,
    name: 'Flow EVM Mainnet',
    shortName: 'Flow',
    symbol: 'FLOW',
    decimals: 18,
    icon: '🌊',
    color: '#00EF8B',
    rpcUrl: 'https://mainnet.evm.nodes.onflow.org',
    explorerUrl: 'https://evm.flowscan.io',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 18. Avalanche C-Chain
  {
    id: 'avalanche',
    chainId: 43114,
    name: 'Avalanche C-Chain',
    shortName: 'Avalanche',
    symbol: 'AVAX',
    decimals: 18,
    icon: '🔺',
    color: '#E84142',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    explorerUrl: 'https://snowtrace.io',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 19. Monad
  {
    id: 'monad',
    chainId: 10143,
    name: 'Monad Network',
    shortName: 'Monad',
    symbol: 'MON',
    decimals: 18,
    icon: '🟣',
    color: '#836EF9',
    rpcUrl: 'https://rpc.monad.xyz',
    explorerUrl: 'https://explorer.monad.xyz',
    category: 'Parallel EVM',
    openseaSupported: true,
  },
  // 20. Somnia
  {
    id: 'somnia',
    chainId: 50312,
    name: 'Somnia Network',
    shortName: 'Somnia',
    symbol: 'STT',
    decimals: 18,
    icon: '✨',
    color: '#FF6B00',
    rpcUrl: 'https://dream-rpc.somnia.network',
    explorerUrl: 'https://somniascan.org',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 21. HyperEVM (Hyperliquid EVM)
  {
    id: 'hyperevm',
    chainId: 998,
    name: 'HyperEVM (Hyperliquid)',
    shortName: 'HyperEVM',
    symbol: 'HYPE',
    decimals: 18,
    icon: '⚡',
    color: '#00F2FE',
    rpcUrl: 'https://rpc.hyperliquid.xyz/evm',
    explorerUrl: 'https://hyperevmscan.io',
    category: 'L1 EVM',
    openseaSupported: true,
  },
  // 22. GUNZ (Gunzilla)
  {
    id: 'gunz',
    chainId: 43419,
    name: 'GUNZ Network',
    shortName: 'GUNZ',
    symbol: 'GUN',
    decimals: 18,
    icon: '🔫',
    color: '#E5E7EB',
    rpcUrl: 'https://rpc.gunz.com',
    explorerUrl: 'https://gunscan.io',
    category: 'Gaming L1',
    openseaSupported: true,
  },
  // 23. Robinhood Chain
  {
    id: 'robinhood',
    chainId: 4001,
    name: 'Robinhood Chain',
    shortName: 'Robinhood',
    symbol: 'ETH',
    decimals: 18,
    icon: '🏹',
    color: '#00C805',
    rpcUrl: 'https://robinhood-chain-rpc.com',
    explorerUrl: 'https://explorer.robinhood.com',
    category: 'Arbitrum Orbit',
    openseaSupported: true,
  },
  // 24. BNB Smart Chain
  {
    id: 'bsc',
    chainId: 56,
    name: 'BNB Smart Chain',
    shortName: 'BNB Chain',
    symbol: 'BNB',
    decimals: 18,
    icon: '🟡',
    color: '#F3BA2F',
    rpcUrl: 'https://bsc-dataseed.binance.org/',
    explorerUrl: 'https://bscscan.com',
    category: 'Layer 1',
    openseaSupported: true,
  },
  // 25. Ink (Kraken L2)
  {
    id: 'ink',
    chainId: 57073,
    name: 'Ink Mainnet (Kraken)',
    shortName: 'Ink',
    symbol: 'ETH',
    decimals: 18,
    icon: '🖋️',
    color: '#9333EA',
    rpcUrl: 'https://rpc-gel.inkonchain.com',
    explorerUrl: 'https://explorer.inkonchain.com',
    category: 'Superchain L2',
    openseaSupported: true,
  },
  // 26. Linea
  {
    id: 'linea',
    chainId: 59144,
    name: 'Linea Mainnet',
    shortName: 'Linea',
    symbol: 'ETH',
    decimals: 18,
    icon: '🖤',
    color: '#121212',
    rpcUrl: 'https://rpc.linea.build',
    explorerUrl: 'https://lineascan.build',
    category: 'zkEVM L2',
    openseaSupported: true,
  },
  // 27. Scroll
  {
    id: 'scroll',
    chainId: 534352,
    name: 'Scroll zkEVM',
    shortName: 'Scroll',
    symbol: 'ETH',
    decimals: 18,
    icon: '📜',
    color: '#FFE7B9',
    rpcUrl: 'https://rpc.scroll.io',
    explorerUrl: 'https://scrollscan.com',
    category: 'zkEVM L2',
    openseaSupported: true,
  },
  // 28. Mantle
  {
    id: 'mantle',
    chainId: 5000,
    name: 'Mantle Network',
    shortName: 'Mantle',
    symbol: 'MNT',
    decimals: 18,
    icon: '🛡️',
    color: '#000000',
    rpcUrl: 'https://rpc.mantle.xyz',
    explorerUrl: 'https://mantlescan.xyz',
    category: 'Layer 2',
    openseaSupported: true,
  },
  // 29. Celo
  {
    id: 'celo',
    chainId: 42220,
    name: 'Celo Mainnet',
    shortName: 'Celo',
    symbol: 'CELO',
    decimals: 18,
    icon: '🌱',
    color: '#35D07F',
    rpcUrl: 'https://forno.celo.org',
    explorerUrl: 'https://celoscan.io',
    category: 'Layer 2',
    openseaSupported: true,
  },
];

export const DEFAULT_CHAIN = SUPPORTED_CHAINS[0]; // Ethereum Mainnet

const CHAIN_ALIASES = {
  'eth': 'ethereum',
  'mainnet': 'ethereum',
  'homestead': 'ethereum',
  'matic': 'polygon',
  'polygon_pos': 'polygon',
  'polygon-pos': 'polygon',
  'arbitrum_one': 'arbitrum',
  'arbitrum-one': 'arbitrum',
  'arbitrum_nova': 'arbitrum',
  'op': 'optimism',
  'optimistic': 'optimism',
  'optimism_mainnet': 'optimism',
  'op_mainnet': 'optimism',
  'avalanche_c': 'avalanche',
  'avalanche-c': 'avalanche',
  'avax': 'avalanche',
  'bnb': 'bsc',
  'binance': 'bsc',
  'robinhood': 'robinhood',
  'robinhood_chain': 'robinhood',
  'robinhood-chain': 'robinhood',
  'hyperliquid': 'hyperevm',
  'hyper_evm': 'hyperevm',
  'b3_network': 'b3',
  'flow_evm': 'flow',
  'gunzilla': 'gunz',
  'sony': 'soneium',
  'sony_l2': 'soneium',
};

export function getChainById(chainIdOrSlug) {
  if (!chainIdOrSlug) return DEFAULT_CHAIN;

  if (typeof chainIdOrSlug === 'number') {
    return SUPPORTED_CHAINS.find((c) => c.chainId === chainIdOrSlug) || DEFAULT_CHAIN;
  }

  const rawQuery = String(chainIdOrSlug).toLowerCase().trim();
  const query = CHAIN_ALIASES[rawQuery] || rawQuery;

  return (
    SUPPORTED_CHAINS.find(
      (c) =>
        c.id === query ||
        c.shortName.toLowerCase() === query ||
        c.name.toLowerCase() === query ||
        c.symbol.toLowerCase() === query ||
        String(c.chainId) === query
    ) || DEFAULT_CHAIN
  );
}
